### ISSUE TITLE
[FEATURE] 2.0版本新功能开发计划

### ISSUE THREAD

**Issue by zds-s** [mineadmin/MineAdmin#112]
中文：
- [x] 对现有的模块控制器完善单元测试
- [x] 在线应用商店
- [x] 在线表单设计
 ...待补充

**Comment by nicesome** [comment]
文档什么时候出来呀

**Comment by Death-Satan** [comment]
> 文档什么时候出来呀

目前来说没什么太大的破坏性改动，只是适配了 hyperf 3.1 and php 8.1+ 看1.x的文档也能用

**Comment by kaxiluo** [comment]
**其他数据源生成CRUD** 小小疑问
感觉可以用database.config里面的配置呀，直接读取其他库的数据，不然针对读取其他库数据的情况还得去本地删除表，改模型的connection。
ps: 一般情况下用户的需求是直接读取其他库数据，不会把其他库的表复制到本地

**Comment by kaxiluo** [comment]
> > **其他数据源生成CRUD** 小小疑问 感觉可以用database.config里面的配置呀，直接读取其他库的数据，不然针对读取其他库数据的情况还得去本地删除表，改模型的connection。 ps: 一般情况下用户的需求是直接读取其他库数据，不会把其他库的表复制到本地
> 
> 配置文件内的加载后，因为连接池的关系，不会变化了，所以才需要用原生的pdo去连接。 未来hyperf若能动态支持，ma也会添加对databse.config的支持

这个不需要动态链接呀，代码生成器都是开发环境使用的

**Comment by condyTao** [comment]
今天修改登陆的，发现了一个神奇的地方，在登陆的时候，直接注入的是UserServiceInterface这个接口，在dependencies里面却没有绑定依赖，但是在后端专区的登录替换中却提到了要绑定依赖(https://doc.mineadmin.com/backend/login.html#dependencies)，
![1715261664615](https://github.com/mineadmin/MineAdmin/assets/54953288/4283bd13-bc1a-4d5f-9e61-8ebb138886b8)
![1715261678280](https://github.com/mineadmin/MineAdmin/assets/54953288/cbab9105-58d3-48f8-bb27-4be4dc82ee21)
![1715261724243](https://github.com/mineadmin/MineAdmin/assets/54953288/97f7c0f7-a10e-4ec4-b391-c646ee0bc373)
