### ISSUE TITLE
2.0[BUG] 

### ISSUE THREAD

**Issue by Johnzero** [mineadmin/MineAdmin#113]
PHP Fatal error:  Declaration of App\Setting\Mapper\SettingConfigMapper::save(array $data): mixed must be compatible with Mine\Abstracts\AbstractMapper::save(array $data): int in /opt/www/app/Setting/Mapper/SettingConfigMapper.php on line 78

**Comment by Death-Satan** [comment]
Thank you for your feedback. This is due to a residual issue in supporting snowflake algorithm IDs. It will be fixed soon
