### ISSUE TITLE
[建议]优化后台定时任务 

### ISSUE THREAD

**Issue by taobali32** [mineadmin/MineAdmin#120]
![image](https://github.com/mineadmin/MineAdmin/assets/30717763/d8dd9e04-477b-4a18-89ee-64613deb18ba)

# 建议1 
增加这4个参数
![image](https://github.com/mineadmin/MineAdmin/assets/30717763/617bbe86-13f9-4e61-9e94-31ba64bb1373)

![image](https://github.com/mineadmin/MineAdmin/assets/30717763/63fc1968-9f61-41f8-868a-626876c8440a)

# 建议2 
扫描系统已有的定时任务注解 给展示到后台， 但是不能编辑 (仅供看)

建议2如果采纳进程启动后载入定时任务时就需要判断下 (仅供看)的就不能在载入一次了的,不然成2次了

**Comment by kanyxmo** [comment]
singleton 是支持的，其他未来支持吧。
建议2先加入计划
