### ISSUE TITLE
[BUG] 后台定时任务有大问题

### ISSUE THREAD

**Issue by taobali32** [mineadmin/MineAdmin#123]
# 版本
使用的2.x的
![image](https://github.com/mineadmin/MineAdmin/assets/30717763/1445990d-ee9d-4808-a797-7ffdb74eadd6)

# 描述
这一坨缓存没啥用
![image](https://github.com/mineadmin/MineAdmin/assets/30717763/49d7193e-4ef7-4df2-a0c7-66d85d6ae94e)

你拿的时候从这里拿的。

下面代码缓存部分感觉暂时没必要，就算后台添加几百上千个定时任务一次拿出来也是很快的。。 
![image](https://github.com/mineadmin/MineAdmin/assets/30717763/7066683c-616d-4975-bd2d-645b99b42500)

**Comment by Death-Satan** [comment]
没有缓存就走下面的db查询了

**Comment by taobali32** [comment]
> 没有缓存就走下面的db查询了

但是你增删改查定时任务了后 缓存不变。。 只能手动去删除redis缓存

**Comment by zds-s** [comment]
已合并到 2.0 最新版本，感谢反馈
