### ISSUE TITLE
代码生成器最新版报错，上一个版本不会 

### ISSUE THREAD

**Issue by cruelwolfking** [mineadmin/MineAdmin#131]
Object of class Mine\Generator\Enums\ComponentTypeEnum could not be converted to string[223] in /Users/mymac/Desktop/php8/mine-actvity-center/MineAdmin/vendor/xmo/mine-generator/src/VueIndexGenerator.ph

**Comment by zds-s** [comment]
https://github.com/mineadmin/MineAdmin/issues/118

**Comment by zds-s** [comment]
composer update后再试一下
