### ISSUE TITLE
[FEATURE] 优化搜索条件对于参数的判定

### ISSUE THREAD

**Issue by xingkoo** [mineadmin/MineAdmin#132]
**Is your feature request related to a problem? Please describe.**
```
    /**
     * 搜索处理器
     * @param Builder $query
     * @param array $params
     * @return Builder
     */
    public function handleSearch(Builder $query, array $params): Builder
    {
        
        // 序号
        if (isset($params['id']) && filled($params['id'])) {
            $query->where('id', '=', $params['id']);
        }
    }
````
如上代码所示，由代码生成器生成。
是否可以，对Query增强，使用类似：
```
// 增加一个方法，用于获取参数
    function param($params, $key, $default=null){
        return (isset($params[$key]) && filled($params['id'])) ? $params[$key]:$default;
    }
    $query->filterWhere('id', '=', getParams($params,'id'))

// or

    $query->filterWhere('id', '=', $params, ,'id')

// or

    isset(isset($params[$key]) &&  $query->filterWhere('id', '=', $params['id'))

```
其中，`filterWhere`可以根据`条件是否为空`来判定`是否使用当前条件`。

事实上类似的场景使用非常多，如果可以优化，能减少不少代码量。
可以参考Yii2的相关处理。
https://github.com/yiisoft/yii2/blob/c2e0485e0a2c0e0c780459a202e65b705ac7fa60/framework/db/QueryTrait.php#L166

**Comment by zds-s** [comment]
该加 if 的还得加，有些场景就是要 0 null 这样的值



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年2月23日(周五) 晚上7:14
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [mineadmin/MineAdmin] [FEATURE] 优化搜索条件对于参数的判定 (Issue #132)




 
Is your feature request related to a problem? Please describe.
     /**      * 搜索处理器      * @param Builder $query      * @param array $params      * @return Builder      */     public function handleSearch(Builder $query, array $params): Builder     {                  // 序号         if (isset($params['id']) &amp;&amp; filled($params['id'])) {             $query-&gt;where('id', '=', $params['id']);         }     }  
如上代码所示，由代码生成器生成。
 是否可以，对Query增强，使用类似：
 // 增加一个方法，用于获取参数     function param($params, $key, $default=null){         return (isset($params[$key]) &amp;&amp; filled($params['id'])) ? $params[$key]:$default;     }     $query-&gt;filterWhere('id', '=', getParams($params,'id')) // or     $query-&gt;filterWhere('id', '=', $params, ,'id') // or     isset(isset($params[$key]) &amp;&amp;  $query-&gt;filterWhere('id', '=', $params['id'))  
其中，filterWhere可以根据条件是否为空来判定是否使用当前条件。
 
事实上类似的场景使用非常多，如果可以优化，能减少不少代码量。
 可以参考Yii2的相关处理。
 https://github.com/yiisoft/yii2/blob/c2e0485e0a2c0e0c780459a202e65b705ac7fa60/framework/db/QueryTrait.php#L166

**Comment by zds-s** [comment]
像这种业务加强型的，封装个组件好了。mine 这个地方回头也打算去掉，类似的效果 hyperf arr 助手已经都有了。非要在后端这块简洁代码的话。不如整体封装一个 FastBuilderWhere 类。
类似
FastBuilderWhere::eq($query,$param,'user')


FastBuilderWhere::like($query,$param,'user')


FastBuilderWhere::likeLeft($query,$param,'user')


FastBuilderWhere::between($query,$param,'user')


FastBuilderWhere::lt($query,$param,'user')




有兴趣的话往 mine-components 下的 mine-helpers 文件夹写个 FastBuilderWhere 类
提个 pr

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年2月23日(周五) 晚上7:14
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [mineadmin/MineAdmin] [FEATURE] 优化搜索条件对于参数的判定 (Issue #132)




 
Is your feature request related to a problem? Please describe.
     /**      * 搜索处理器      * @param Builder $query      * @param array $params      * @return Builder      */     public function handleSearch(Builder $query, array $params): Builder     {                  // 序号         if (isset($params['id']) &amp;&amp; filled($params['id'])) {             $query-&gt;where('id', '=', $params['id']);         }     }  
如上代码所示，由代码生成器生成。
 是否可以，对Query增强，使用类似：
 // 增加一个方法，用于获取参数     function param($params, $key, $default=null){         return (isset($params[$key]) &amp;&amp; filled($params['id'])) ? $params[$key]:$default;     }     $query-&gt;filterWhere('id', '=', getParams($params,'id')) // or     $query-&gt;filterWhere('id', '=', $params, ,'id') // or     isset(isset($params[$key]) &amp;&amp;  $query-&gt;filterWhere('id', '=', $params['id'))  
其中，filterWhere可以根据条件是否为空来判定是否使用当前条件。
 
事实上类似的场景使用非常多，如果可以优化，能减少不少代码量。
 可以参考Yii2的相关处理。
 https://github.com/yiisoft/yii2/blob/c2e0485e0a2c0e0c780459a202e65b705ac7fa60/framework/db/QueryTrait.php#L166
