### ISSUE TITLE
[QUESTION] 请教用户选择器单选用户的用法。

### ISSUE THREAD

**Issue by xingkoo** [mineadmin/MineAdmin#133]
新入坑，虚心求教。
用户选择器，
```
  {
    title: "户主",
    dataIndex: "account_owner_id",
    formType: "user-select",
    multiple: false,
    search: true,
    onlyId: true
  }
```
此时，选择器可以单选，选择出来的结果还是个数组`[$id]`。我需要提交的是个独立的`id`即可。
我不确认是我没有发现，有可以让组件返回具体属性而非字段的功能，还是目前仅支持返回数组格式。
如果后者，应该如何处理数据？是否有相应的事件可以修改选择器返回的结果，将期变更为具体`id`。
亦或者应试使用一个辅助属性，通过选择后使用变更事件，来修改真实的`account_owner_id`

**Comment by xingkoo** [comment]
我的理解，当设置`multiple: false`后，应该是返回具体的值，而非依然以单元素数组格式返回，更符合用法。

**Comment by zds-s** [comment]
官网有q群，前端我不太懂。可以进群一起交流



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年2月25日(周日) 下午4:46
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [mineadmin/MineAdmin] [QUESTION] 请教用户选择器单选用户的用法。 (Issue #133)




 
如果是关联变更，cascaderItem仅支持select和radio，有没有什么方法，可以直接变更另外的值，这样可以显示一个助手列，用于显示选择器，选择后修改实际列。
