### ISSUE TITLE
[BUG] OSS配置上传无法生效

### ISSUE THREAD

**Issue by huangmangit** [mineadmin/MineAdmin#166]
### bug描述:
配置好其他OSS后，无法进行上传到其他OSS中，仍然是默认的本地上传，查看源码后发现，下列代码处
```
vendor/xmo/mine-core/src/MineUpload.php
```
中构造函数中
```
...
$this->filesystem = $factory->get(match ($this->getStorageMode()) {
    2 => 'oss',
    3 => 'qiniu',
    4 => 'cos',
    default => 'local'
});
...
```
$this->getStorageMode() 方法中返回的是数据库表setting_config的value字段的值类型，该字段为varchar类型，而在构造函数中匹配的是数字，所以导致存储工厂一直获取的是默认值local本地存储方式。
### 修复方法:
鉴于该类中有类似的判断方法（getMappingMode）但没有使用过且类型非常全，可将此处构造方法中替换为：
```
...
$this->filesystem = $factory->get($this->getMappingMode())
...
```

**Comment by zds-s** [comment]
感谢反馈，已修复 https://github.com/mineadmin/mine-components/pull/30

换成删除 vendor 换成官方源重新更新一下
或者先用 class_map 替换一下该文件使用
