### ISSUE TITLE
请问下，我的数据表没有带模块前缀，如何生成代码啊

### ISSUE THREAD

**Issue by cxjhk** [mineadmin/MineAdmin#169]
数据库是三方的数据库，表名设计各式各样，无法根据模块 比如 setting_xx来命名

请问下这种情况如何生成代码

**Comment by zds-s** [comment]
没办法生成，目前的一键代码生成是基于模块化的。像这样的情况，建议你熟悉熟悉代码生成那块的东西。都是现成的 api。自己基于这个写一套你自己的转换规则 具体可以看看 [mine-generator](https://github.com/mineadmin/mine-generator) 这个仓库 2.0 分支代码

**Comment by cxjhk** [comment]
好吧，那暂时用不了了

**Comment by zds-s** [comment]
一键 crud 这块功能本身就是用来快速从 0 到 1 的开发的。想从其他系统转换到 mine 里面，还不如直接约定好模块名然后再开发

**Comment by cxjhk** [comment]
没办法，有些业务 依赖三方，只是给他们做个查看哪些，我手动复制得了

**Comment by zds-s** [comment]
已解决，Close
