### ISSUE TITLE
VueIndexGenerator.php

### ISSUE THREAD

**Issue by fsg-herbie** [mineadmin/MineAdmin#172]
第 294行，未添加查询，插入，列表，编辑选框状态的判断，导致生成index.vue列出了全部字段，建议添加过滤，根据代码生成器编辑复选框对应字段生成代码。
在第 294行处插入

// 这里需要过滤未选择的列，如果四大皆空，即是空，南无阿弥陀佛
if ($column->is_query == self::NO && $column->is_insert == self::NO && $column->is_edit == self::NO && $column->is_list == self::NO) {
    continue;
}

**Comment by zds-s** [comment]
查询列表感觉自己手动处理一下就好了

**Comment by zds-s** [comment]
No feedback
