### ISSUE TITLE
[QUESTION]  redis健名称

### ISSUE THREAD

**Issue by okami-chen** [mineadmin/MineAdmin#182]
## Before you submit this issue, you has been search all existed issues and search the [documentation](https://hyperf.wiki)

`upload_mode`、`queue_msg_type`等，前面都增加多了一个`_`
```
skeleton:dev:system:config:value:_upload_mode
skeleton:dev:system:dict:data:_queue_msg_type
```

### Describe your question

**Comment by zds-s** [comment]
注解

**Comment by zds-s** [comment]
这些地方注解就是前面加了个 `_ ` ，可以自己配置一下
