### ISSUE TITLE
[BUG] 恢复和删除操作同时出现了

### ISSUE THREAD

**Issue by okami-chen** [mineadmin/MineAdmin#190]
执行命令并粘贴以下结果。

Command: `uname -a && php -v && composer info | grep mine && php --ri swoole`

```bash

```

### bug描述:
  显示回收站数据的时候，同时出现了行内操作同时出现了 `恢复` 和`删除`

### 重现步骤:

文件`column.vue`需要加个判断

```
<a-popconfirm 
    content="确定要删除该数据吗?"
    position="bottom"
    @ok="deleteAction(record)"
    v-if="(isFunction(options.delete.show) ? options.delete.show(record) : options.delete.show)"
>
  <a-link
      type="primary"
      v-auth="options.delete.auth || []"
      v-role="options.delete.role || []"
      :disabled="(isFunction(options.delete.disabled) ? options.delete.disabled(record) : options.delete.disabled)"
  >
    <icon-delete />
    {{
      props.isRecovery ? options.delete.realText || '删除' : options.delete.text || '删除'
    }}
  </a-link>
</a-popconfirm>

```

**Comment by zds-s** [comment]
提个pr吧



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月16日(周六) 上午10:32
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [mineadmin/MineAdmin] [BUG] 恢复和删除操作同时出现了 (Issue #190)




 
执行命令并粘贴以下结果。
 
Command: uname -a &amp;&amp; php -v &amp;&amp; composer info | grep mine &amp;&amp; php --ri swoole
 # Paste the result here.
 
bug描述:
 
显示回收站数据的时候，同时出现了行内操作同时出现了 恢复 和删除
 
重现步骤:
 
文件column.vue需要加个判断
                   <a-popconfirm                        content="确定要删除该数据吗?"                       position="bottom"                       @ok="deleteAction(record)"                       v-if="(isFunction(options.delete.show) ? options.delete.show(record) : options.delete.show)"                   &gt;                     <a-link                         type="primary"                         v-auth="options.delete.auth || []"                         v-role="options.delete.role || []"                         :disabled="(isFunction(options.delete.disabled) ? options.delete.disabled(record) : options.delete.disabled)"                     &gt;                       <icon-delete /&gt;                       {{                         props.isRecovery ? options.delete.realText || '删除' : options.delete.text || '删除'                       }}                     </a-link&gt;                   </a-popconfirm&gt;

**Comment by kanyxmo** [comment]
没毛病，第一次删除是软删除，回收站的删除是物理删除了
