### ISSUE TITLE
使用 docke-composer install  时候提示报错

### ISSUE THREAD

**Issue by jackchang1025** [mineadmin/MineAdmin#195]
![image](https://github.com/mineadmin/MineAdmin/assets/71494064/8e80ef92-92aa-4421-ac0d-b954793730d4)

这是 容器运行情况
![image](https://github.com/mineadmin/MineAdmin/assets/71494064/4901d434-bc11-4825-ba53-165a8d93af56)

下面是.env 文件
APP_NAME = MineAdmin
APP_ENV = dev
DB_DRIVER = mysql
DB_HOST = mysql
DB_PORT = 3306
DB_DATABASE = mineadmin
DB_USERNAME = root
DB_PASSWORD = 12345678
DB_CHARSET = utf8mb4
DB_COLLATION = utf8mb4_general_ci
DB_PREFIX = 

REDIS_HOST = redis
REDIS_AUTH = (NULL)
REDIS_PORT = 6379
REDIS_DB = 0

**Comment by zds-s** [comment]
需要mysql容器创建数据库。默认没有 mineadmin 数据库
