### ISSUE TITLE
[QUESTION] 模型fillable动态修改

### ISSUE THREAD

**Issue by tiancheng-66** [mineadmin/MineAdmin#196]
![4369ec0d153b8d00e0856eb21b08e543](https://github.com/mineadmin/MineAdmin/assets/32589267/825eda20-c80f-4fdc-bd3f-6c32539d0382)
我想实现一个在模型加载时动态修改fillable的功能 打印出来fillable是添加进去了但是我实际在写入数据时在new一个新的模型时我添加的数据不存在了这是为什么呢
![8795c71665a8fd69167d282f9e9b9096](https://github.com/mineadmin/MineAdmin/assets/32589267/bc45e84d-7b68-4186-b74a-a547b9efd5e9)

**Comment by zds-s** [comment]
操作的不是一个对象

**Comment by tiancheng-66** [comment]
> 操作的不是一个对象

但是我在每次模型加载的时候都会去增加上呀 有监听booting::class
new $this->model()的时候不会走到booting吗

**Comment by zds-s** [comment]
https://learnku.com/docs/laravel/10.x/eloquent/14888
