### ISSUE TITLE
[BUG] 容器镜像内置环境，php 的 composer install 提示需要php8.1版本，镜像该更新了

### ISSUE THREAD

**Issue by 521chy** [mineadmin/MineAdmin#198]
执行命令并粘贴以下结果。

Command: `uname -a && php -v && composer info | grep mine && php --ri swoole`

```bash
# Paste the result here.

Linux ac7ab01e0049 6.1.0-18-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.76-1 (2024-02-01) x86_64 Linux
PHP 8.0.16 (cli) (built: Feb 19 2022 04:12:59) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.16, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.16, Copyright (c), by Zend Technologies
Composer could not find a composer.json file in /etc
To initialize a project, please create a composer.json file. See https://getcomposer.org/basic-usage

### bug描述:
 Problem 1
    - Root composer.json requires xmo/jwt-auth 2.0.x-dev -> satisfiable by xmo/jwt-auth[2.0.x-dev].
    - xmo/jwt-auth 2.0.x-dev requires php >=8.1 -> your php version (8.0.16) does not satisfy that requirement.
  Problem 2
    - Root composer.json requires xmo/mine-core 2.0.x-dev -> satisfiable by xmo/mine-core[2.0.x-dev].
    - xmo/mine-core 2.0.x-dev requires php >=8.1 -> your php version (8.0.16) does not satisfy that requirement.
  Problem 3
    - Root composer.json requires xmo/mine-generator 2.0.x-dev -> satisfiable by xmo/mine-generator[2.0.x-dev].
    - xmo/mine-generator 2.0.x-dev requires php >=8.1 -> your php version (8.0.16) does not satisfy that requirement.
  Problem 4
    - Root composer.json requires xmo/mine-helpers 2.0.x-dev -> satisfiable by xmo/mine-helpers[2.0.x-dev].
    - xmo/mine-helpers 2.0.x-dev requires php >=8.1 -> your php version (8.0.16) does not satisfy that requirement.
  Problem 5
    - Root composer.json requires xmo/mine-office 2.0.x-dev -> satisfiable by xmo/mine-office[2.0.x-dev].
    - xmo/mine-office 2.0.x-dev requires php >=8.1 -> your php version (8.0.16) does not satisfy that requirement.
  Problem 6
    - Root composer.json requires xmo/mine-service 2.0.x-dev -> satisfiable by xmo/mine-service[2.0.x-dev].
    - xmo/mine-service 2.0.x-dev requires php >=8.1 -> your php version (8.0.16) does not satisfy that requirement.
  Problem 7
    - Root composer.json requires xmo/mine-translatable 2.0.x-dev -> satisfiable by xmo/mine-translatable[2.0.x-dev].
    - xmo/mine-translatable 2.0.x-dev requires php >=8.1 -> your php version (8.0.16) does not satisfy that requirement.
  Problem 8
    - Root composer.json requires hyperf/devtool 3.1.* -> satisfiable by hyperf/devtool[v3.1.0-alpha.1, ..., 3.1.x-dev].
    - hyperf/devtool[v3.1.0-alpha.1, ..., 3.1.x-dev] require php >=8.1 -> your php version (8.0.16) does not satisfy that requirement.
  Problem 9

### 重现步骤:

**Comment by zds-s** [comment]
文档里面的镜像不维护了。用 master 分支的 docketfile



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月19日(周二) 上午8:57
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [mineadmin/MineAdmin] [BUG] 容器镜像内置环境，php 的 composer install 提示需要php8.1版本，镜像该更新了 (Issue #198)




 
执行命令并粘贴以下结果。
 
Command: uname -a &amp;&amp; php -v &amp;&amp; composer info | grep mine &amp;&amp; php --ri swoole
 # Paste the result here. Linux ac7ab01e0049 6.1.0-18-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.76-1 (2024-02-01) x86_64 Linux PHP 8.0.16 (cli) (built: Feb 19 2022 04:12:59) ( NTS ) Copyright (c) The PHP Group Zend Engine v4.0.16, Copyright (c) Zend Technologies     with Zend OPcache v8.0.16, Copyright (c), by Zend Technologies Composer could not find a composer.json file in /etc To initialize a project, please create a composer.json file. See https://getcomposer.org/basic-usage ### bug描述:  Problem 1     - Root composer.json requires xmo/jwt-auth 2.0.x-dev -&gt; satisfiable by xmo/jwt-auth[2.0.x-dev].     - xmo/jwt-auth 2.0.x-dev requires php &gt;=8.1 -&gt; your php version (8.0.16) does not satisfy that requirement.   Problem 2     - Root composer.json requires xmo/mine-core 2.0.x-dev -&gt; satisfiable by xmo/mine-core[2.0.x-dev].     - xmo/mine-core 2.0.x-dev requires php &gt;=8.1 -&gt; your php version (8.0.16) does not satisfy that requirement.   Problem 3     - Root composer.json requires xmo/mine-generator 2.0.x-dev -&gt; satisfiable by xmo/mine-generator[2.0.x-dev].     - xmo/mine-generator 2.0.x-dev requires php &gt;=8.1 -&gt; your php version (8.0.16) does not satisfy that requirement.   Problem 4     - Root composer.json requires xmo/mine-helpers 2.0.x-dev -&gt; satisfiable by xmo/mine-helpers[2.0.x-dev].     - xmo/mine-helpers 2.0.x-dev requires php &gt;=8.1 -&gt; your php version (8.0.16) does not satisfy that requirement.   Problem 5     - Root composer.json requires xmo/mine-office 2.0.x-dev -&gt; satisfiable by xmo/mine-office[2.0.x-dev].     - xmo/mine-office 2.0.x-dev requires php &gt;=8.1 -&gt; your php version (8.0.16) does not satisfy that requirement.   Problem 6     - Root composer.json requires xmo/mine-service 2.0.x-dev -&gt; satisfiable by xmo/mine-service[2.0.x-dev].     - xmo/mine-service 2.0.x-dev requires php &gt;=8.1 -&gt; your php version (8.0.16) does not satisfy that requirement.   Problem 7     - Root composer.json requires xmo/mine-translatable 2.0.x-dev -&gt; satisfiable by xmo/mine-translatable[2.0.x-dev].     - xmo/mine-translatable 2.0.x-dev requires php &gt;=8.1 -&gt; your php version (8.0.16) does not satisfy that requirement.   Problem 8     - Root composer.json requires hyperf/devtool 3.1.* -&gt; satisfiable by hyperf/devtool[v3.1.0-alpha.1, ..., 3.1.x-dev].     - hyperf/devtool[v3.1.0-alpha.1, ..., 3.1.x-dev] require php &gt;=8.1 -&gt; your php version (8.0.16) does not satisfy that requirement.   Problem 9 ### 重现步骤:

**Comment by 521chy** [comment]
建议更新以下文档。嗯，项目很棒，加油
