### ISSUE TITLE
[BUG] 配置项输入组件数据源问题

### ISSUE THREAD

**Issue by lnermif** [mineadmin/MineAdmin#214]
执行命令并粘贴以下结果。

Command: `uname -a && php -v && composer info | grep mine && php --ri swoole`

```bash
# Paste the result here.
```

### bug描述:
系统设置 配置项的输入组件单选、复选数据源 无法在输入框内编辑，只能在外部编辑好数据源在粘贴进去。
在右侧添加该组配置项后，左侧无法正常显示组件options，需要整页刷新

### 重现步骤:

**Comment by kanyxmo** [comment]
编辑器问题，更新下新版前端
