### ISSUE TITLE
新版本2.0里面ma-crud里面的表单卡槽怎么绑定值提交呢？

### ISSUE THREAD

**Issue by bingxinti** [mineadmin/MineAdmin#216]
ma-crud的自定义卡槽我看了，有  自定义组件。 我感觉有点麻烦。
就想着用ma-form里面的    自定义表单卡槽，

<template>
    
    <ma-form v-model="form" :columns="columnsOptions" ref="crudForm" @onSubmit="handlerSubmit" />
        <template #form-username>
            <a-input v-model="form['username']" placeholder="请输入用户名" />
        </template>
    </ma-form>
</template>

但是ma-crud里面提交值的时候，没有username 提交，  然后也获取不到form，  怎么办呢？
有没有快捷的优雅写法～～

**Comment by kanyxmo** [comment]
想有username字段，先在columns里配置一个，给列表设置隐藏，然后再用插槽写，内部组件会过滤掉不存在columns的属性值。
