### ISSUE TITLE
用户中心为什么是公司内部人员？而不是管理注册的用户/客户的。

### ISSUE THREAD

**Issue by qzuozhu** [mineadmin/MineAdmin#220]
用户中心不应该是管理注册的用户的吗？

**Comment by zds-s** [comment]
user_type = 100 系统用户
user_type = ? 自定义

**Comment by qzuozhu** [comment]
前后台用户没有分开，会不会有点混乱？像我们公司前端就有很多角色。

**Comment by zds-s** [comment]
角色权限上的分辨？

**Comment by zds-s** [comment]
你说的是用户中心，这是后台管理系统。前台用户中心需要你们自己写ui。或者以角色，权限的形式分开



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年4月10日(周三) 下午5:33
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [mineadmin/MineAdmin] 用户中心为什么是公司内部人员？而不是管理注册的用户/客户的。 (Issue #220)




 
前后台用户没有分开，会不会有点混乱？像我们公司前端就有很多角色。

**Comment by qzuozhu** [comment]
我意思是后台的admin和前台的user数据放在一起了，但前提的数据结构不一样的。

**Comment by zds-s** [comment]
多商户的话。用角色分辨最简单。不同角色展示不同菜单。菜单对应控制器调用自己的数据查询。这只是个骨架，具体怎么写还是开发者决定



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年4月10日(周三) 下午5:58
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [mineadmin/MineAdmin] 用户中心为什么是公司内部人员？而不是管理注册的用户/客户的。 (Issue #220)




 
是的，我看你这个用户中心就是后台的，不是前台的。我们线上是b2b2c，有个人也有公司也有供应商，数据结构都是不一样的。

**Comment by qzuozhu** [comment]
您这个需要收费吗？免费商用的吗？

**Comment by zds-s** [comment]
免费可商用。具体规则可以了解下 Apache2.0 许可证内容



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年4月10日(周三) 晚上6:08
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [mineadmin/MineAdmin] 用户中心为什么是公司内部人员？而不是管理注册的用户/客户的。 (Issue #220)




 
您这个需要收费吗？免费商用的吗？

**Comment by qzuozhu** [comment]
我发现个问题，点击编辑用户，3次请求同样数据。
![9999999999999999](https://github.com/mineadmin/MineAdmin/assets/29276259/24ade056-3706-4b35-aece-b883d87cd514)

**Comment by zds-s** [comment]
demo 示例的版本比较老

**Comment by libaipengl** [comment]
异常怎么抛出

**Comment by zds-s** [comment]
> 异常怎么抛出

throw new NormalException
