### ISSUE TITLE
上传图片成功后 返回图片id 并入库[FEATURE] 

### ISSUE THREAD

**Issue by libaipengl** [mineadmin/MineAdmin#234]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by zds-s** [comment]
@docubot 帮忙用中文解答一下这个标题

**Comment by libaipeng1314** [comment]
如何做多语言

**Comment by zds-s** [comment]
> 如何做多语言

hyperf 正常怎么做你就怎么搞

**Comment by zds-s** [comment]
ma-upload 设置返回类型为 hash。
