### ISSUE TITLE
兼容composer生态吗？

### ISSUE THREAD

**Issue by qzuozhu** [mineadmin/MineAdmin#249]

**Comment by zds-s** [comment]
兼容



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月7日(周二) 下午3:13
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [mineadmin/MineAdmin] 兼容composer生态吗？ (Issue #249)

**Comment by qzuozhu** [comment]
其实我想问的是生态够不够丰富？非hyperf版本的一些类库能不能直接使用？

**Comment by zds-s** [comment]
对于 composer 生态、hyperf 和 webman 都不能保证所有的都兼容。但是基本上都是能覆盖 70 ~ 90 % 的包
