### ISSUE TITLE
今天修改登陆的，发现了一个神奇的地方，在登陆的时候，直接注入的是UserServiceInterface这个接口，在dependencies里面却没有绑定依赖，但是在后端专区的登录替换中却提到了要绑定依赖(https://doc.mineadmin.com/backend/login.html#dependencies)，

### ISSUE THREAD

**Issue by zds-s** [mineadmin/MineAdmin#251]
今天修改登陆的，发现了一个神奇的地方，在登陆的时候，直接注入的是UserServiceInterface这个接口，在dependencies里面却没有绑定依赖，但是在后端专区的登录替换中却提到了要绑定依赖(https://doc.mineadmin.com/backend/login.html#dependencies)，
![1715261664615](https://github.com/mineadmin/MineAdmin/assets/54953288/4283bd13-bc1a-4d5f-9e61-8ebb138886b8)
![1715261678280](https://github.com/mineadmin/MineAdmin/assets/54953288/cbab9105-58d3-48f8-bb27-4be4dc82ee21)
![1715261724243](https://github.com/mineadmin/MineAdmin/assets/54953288/97f7c0f7-a10e-4ec4-b391-c646ee0bc373)

_Originally posted by @condyTao in https://github.com/mineadmin/MineAdmin/issues/112#issuecomment-2102682278_

**Comment by zds-s** [comment]
@condyTao 这里的意思是，如果需要自定义 UserService、可以替换依赖。默认的 userService 由 [mine-core](https://github.com/mineadmin/mine-core) 提供了

**Comment by condyTao** [comment]
我知道在mine-core里面有一个UserServiceInterface，但是没有找到userService
