### ISSUE TITLE
安装时出现问题

### ISSUE THREAD

**Issue by rolkey** [mineadmin/MineAdmin#254]
执行命令

```bash
composer install -vvv
```

### bug描述:
出现如下错误：
---------------------------------------------------------------------------------------------
In CurlDownloader.php line 630:
                                                                                                                              
  [Composer\Downloader\TransportException (404)]                                                                              
  The "https://mirrors.cloud.tencent.com/repository/composer/p/xmo/mine-core.json" file could not be downloaded (HTTP/1.1 40  
  4 Not Found)

**Comment by zds-s** [comment]
mine-core 版本多少

**Comment by rolkey** [comment]
单独安装有问题，不过后面换Deocker已经解决
