### ISSUE TITLE
第三方类库registerUserDataScope函数怎么修改

### ISSUE THREAD

**Issue by bingxinti** [mineadmin/MineAdmin#257]
你好，我有一个问题，我的后台是加了租户的概念，  然后修改数据权限逻辑。
需要修改类库里面的 registerUserDataScope 函数，怎么修改第三方库里面的代码呢？

**Comment by zds-s** [comment]
aspect 或者 class map



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月15日(周三) 凌晨1:16
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [mineadmin/MineAdmin] 第三方类库registerUserDataScope函数怎么修改 (Issue #257)




 
你好，我有一个问题，我的后台是加了租户的概念，  然后修改数据权限逻辑。
 需要修改类库里面的 registerUserDataScope 函数，怎么修改第三方库里面的代码呢？
