### ISSUE TITLE
[QUESTION] 

### ISSUE THREAD

**Issue by philstartup** [mineadmin/MineAdmin#261]
## Before you submit this issue, you has been search all existed issues and search the [documentation](https://hyperf.wiki)
- [√] I've been search all existed issues
- [√] I've been read all documentation

### Describe your question
mapper层不能调用update 报 Call to a member function update() on null[319] in /www/wm-php/vendor/xmo/mine-core/src/Traits/MapperTrait.php
是哪里用错了吗？
![image](https://github.com/mineadmin/MineAdmin/assets/16739904/15b71e56-26a9-4ef8-be9f-7428d7a7a1e4)

**Comment by zds-s** [comment]
用 this
