### ISSUE TITLE
在页面点击一个链接的时候，最终又会重定向回首页来，而且会把这个链接的地址加在浏览器输入框中的http://localhost:2888/这个后面

### ISSUE THREAD

**Issue by condyTao** [mineadmin/MineAdmin#262]
![QQ图片20240521124115](https://github.com/mineadmin/MineAdmin/assets/54953288/7ab3264f-541b-4000-9e4f-4598e074c536)
![QQ图片20240521124133](https://github.com/mineadmin/MineAdmin/assets/54953288/2b67db85-9227-42c1-9182-44ff99b4c185)
![QQ图片20240521124125](https://github.com/mineadmin/MineAdmin/assets/54953288/f5236f15-46b1-46ff-ab09-cd5fb0bd4c14)

**Comment by zds-s** [comment]
加上协议前缀试试
