### ISSUE TITLE
[BUG] 数据装载问题

### ISSUE THREAD

**Issue by jnewer** [mineadmin/MineAdmin#276]
执行命令并粘贴以下结果。

Command: `uname -a && php -v && composer info | grep mine && php --ri swoole`

```bash
# Paste the result here.
```

### bug描述:
1、代码生成器数据装载没有对表名验重，可以重复装载
![image](https://github.com/mineadmin/MineAdmin/assets/14370900/8df5916b-7be8-4d58-aad8-b6b1c19d03a5)
2、新装载的数据表由于没有所属模块，预览时会报以下错误
![image](https://github.com/mineadmin/MineAdmin/assets/14370900/f1310d51-08f5-4f13-a1d0-8772c5090486)

### 重现步骤:

**Comment by zds-s** [comment]
@netyum 有时间看看

**Comment by zds-s** [comment]
model 重写一下这个方法。给一个模块好了
