### ISSUE TITLE
[BUG] phar打包后运行失败

### ISSUE THREAD

**Issue by taobali32** [mineadmin/MineAdmin#288]
执行命令并粘贴以下结果。

php bin/hyperf.php phar:build
打包后使用swoole-cli运行出错，swoole-cli php版本php 8.2.18,（排除swoole-cli和phar问题的）

### bug描述:
使用mineAdmin源码 无添加任何操作后打包后运行的

我已解决到这一步了， 但是忘记了hyperf的ConfigProvider加载流程了，就没继续了
<img width="1409" alt="image" src="https://github.com/mineadmin/MineAdmin/assets/30717763/68e01587-cde3-4f7e-9ddc-87237c665d1b">

### 修改步骤:
<img width="1579" alt="image" src="https://github.com/mineadmin/MineAdmin/assets/30717763/4719bd0e-67b8-46d6-a6cb-e29a2b5dd855">

<img width="1512" alt="image" src="https://github.com/mineadmin/MineAdmin/assets/30717763/be91a205-eace-4e4c-b541-c34932094acd">

**Comment by People-Sea** [comment]
已修复，拉最新代码

**Comment by taobali32** [comment]
> 最新



> 已修复，拉最新代码

修复提交的pr id是多少呢， 没看到有修复代码， 老代码不能拉代码升级.

**Comment by People-Sea** [comment]
> > 最新
> 
> > 已修复，拉最新代码
> 
> 修复提交的pr id是多少呢， 没看到有修复代码， 老代码不能拉代码升级.

重新composer install 一下 更新的依赖 appstore 库 [mineadmin/](https://packagist.org/packages/mineadmin/)app-store

**Comment by People-Sea** [comment]
> > 最新
> 
> > 已修复，拉最新代码
> 
> 修复提交的pr id是多少呢， 没看到有修复代码， 老代码不能拉代码升级.

`if (! empty($info['composer']['config']) && class_exists($info['composer']['config'])) {` Issues 截图中

**Comment by taobali32** [comment]
> > > 最新
> > 
> > 
> > > 已修复，拉最新代码
> > 
> > 
> > 修复提交的pr id是多少呢， 没看到有修复代码， 老代码不能拉代码升级.
> 
> `if (! empty($info['composer']['config']) && class_exists($info['composer']['config'])) {` Issues 截图中43行修改成这个

这不行的，属于临时解决， 真正解决应该让phar扫描插件目录的， phar包目前只扫描composer.lock文件，我尝试加了phar扫描 psr-4  就是 插件目录，试了没成功。  

还是打包docker吧，不用phar了。

**Comment by zds-s** [comment]
phar 他实际就是个压缩包了，你把 mine  的 api common plugin 目录都打到 phar 里面还会有这个问题吗

**Comment by taobali32** [comment]
> phar 他实际就是个压缩包了，你把 mine 的 api common plugin 目录都打到 phar 里面还会有这个问题吗

不行，没有加载psr依赖。 只是打包进去是不行的，  或者我的使用方式有问题。  还是docker吧 方便省事

**Comment by People-Sea** [comment]
折腾了半天压缩出来正常运行了  glob 函数 和  realpath phar环境内 不能正常返回 
剩下的点就是 runtime  uploadfiles 文件配置好系统绝对路径
