### ISSUE TITLE
[QUESTION] 请问怎么关闭终端的sql查询语句？

### ISSUE THREAD

**Issue by van23qf** [mineadmin/MineAdmin#296]
我需要开启dev，并且开启info日志，同时关掉sql语句输出，请问要怎么做？屏幕大量输出sql日志，严重干扰我正常debug

**Comment by ShaBaoFa** [comment]
`.env`  文件中 `CONSOLE_SQL=true` 修改为 `CONSOLE_SQL=falese` 即可
