### ISSUE TITLE
[BUG] 设置searchDefaultValue后，第一次请求没有带上默认查询条件参数，且修改该搜索字段内容时点击搜索也不会携带该参数的默认搜索值

### ISSUE THREAD

**Issue by afie1994** [mineadmin/MineAdmin#324]
执行命令并粘贴以下结果。
 
### bug描述:
设置searchDefaultValue后，第一次请求没有带上默认查询条件参数值，且如果不修改该搜索字段值直接点击搜索仍然不会携带该参数的默认搜索值。

### 重现步骤:
![企业微信截图_1722764634429](https://github.com/user-attachments/assets/9ba3e198-fa5c-4a97-a728-5a14b5caef4c)
![企业微信截图_17227647514093](https://github.com/user-attachments/assets/a511e79e-3c04-4147-8a6f-28bd2db23eef)
![企业微信截图_17227648471021](https://github.com/user-attachments/assets/601470b5-a662-4833-86c5-d71f20c1ad67)

**Comment by zds-s** [comment]
用 beforeRequest 吧
