### ISSUE TITLE
pestphp/pest-plugin-arch 这个插件报错

### ISSUE THREAD

**Issue by cruelwolfking** [mineadmin/MineAdmin#339]
pestphp/pest[v2.33.1, ..., 2.x-dev] require pestphp/pest-plugin-arch ^2.7.0 -> satisfiable by pestphp/pest-plugin-arch[v2.7.0, 2.x-dev].
    - pestphp/pest v2.33.0 requires pestphp/pest-plugin-arch ^2.6.1 -> satisfiable by pestphp/pest-plugin-arch[v2.6.1, v2.7.0, 2.x-dev].
    - pestphp/pest-plugin-arch[v2.6.1, ..., 2.x-dev] require ta-tikoma/phpunit-architecture-test ^0.8.4 -> found ta-tikoma/phpunit-architecture-test[dev-main, 0.1.0, ..., 0.8.3] but it does not match the constraint.
    - Root composer.json requires pestphp/pest ^2.33 -> satisfiable by pestphp/pest[v2.33.0, ..., 2.x-dev].

**Comment by zds-s** [comment]
换官方源
