### ISSUE TITLE
[QUESTION] rabbitmq客户端一直断连然后重启，必须重启hyperf才能正常

### ISSUE THREAD

**Issue by vingin007** [mineadmin/MineAdmin#346]
## Before you submit this issue, you has been search all existed issues and search the [documentation](https://hyperf.wiki)
- [✅] I've been search all existed issues
- [✅] I've been read all documentation

### Describe your question
<img width="563" alt="image" src="https://github.com/user-attachments/assets/71820461-3aa8-4745-ad67-30e52e31b803">
rabbitmq客户端一直断连然后重启，必须重启hyperf才能正常。项目是用docker启动，用1panel管理的。调试日志里也没看到有报错，因为出问题一般是在后半夜，也看不到控制台输出，有什么办法可以定位问题？

**Comment by zds-s** [comment]
提到 hyperf 那边反馈吧。amqp 组件 mine 这边没做太多处理

**Comment by vingin007** [comment]
好的
