### ISSUE TITLE
[BUG] 希望修改默认配置

### ISSUE THREAD

**Issue by DanRan-hcy** [mineadmin/MineAdmin#348]
1. /.env.example 文件中的， DB_HOST、REDIS_HOST等默认值都是localhost，希望更改为服务名称，第一次用的人不熟悉会安装失败。
2. php bin/hyperf.php mine:install 执行时没有自动创建数据库，建议加入。或者更新一下安装文档。

**Comment by zds-s** [comment]
@People-Sea

**Comment by People-Sea** [comment]
晚上处理
