### ISSUE TITLE
请问作者是否考虑做一个Laravel版本的后端版本

### ISSUE THREAD

**Issue by KitePig** [mineadmin/MineAdmin#364]
Laravel 用着更加顺手些。用户群体也大

**Comment by zds-s** [comment]
laravel 已经有很多人在写 admin 了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年10月17日(周四) 晚上8:17
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [mineadmin/MineAdmin] 请问作者是否考虑做一个Laravel版本的后端版本 (Issue #364)




 
Laravel 用着更加顺手些。用户群体也大

**Comment by KitePig** [comment]
你这个UI比其他的好看
