### ISSUE TITLE
[BUG] 插件中的swagger会覆盖替换主体swagger

### ISSUE THREAD

**Issue by vatezj** [mineadmin/MineAdmin#455]
执行命令并粘贴以下结果。

Command: `uname -a && php -v && composer info | grep mine && php --ri swoole`

```bash
# Paste the result here.
```

### 重现步骤:

**Comment by zds-s** [comment]
覆盖替换是指?

**Comment by vatezj** [comment]
![image](https://github.com/user-attachments/assets/aa0f3ef5-c3cc-41e9-898a-751ac56cd718)

**Comment by vatezj** [comment]
> 覆盖替换是指?

![image](https://github.com/user-attachments/assets/2e96c7d0-43ab-46d5-a763-9e58dcffb13f)

**Comment by zds-s** [comment]
把 `plugin/mine-admin/code-generator/src/configProvider` 文件中的 swagger 先去掉。这个有时间优化一下。感谢反馈
