### ISSUE TITLE
安装code-generator报错，如何解决？

### ISSUE THREAD

**Issue by dmskys** [mineadmin/MineAdmin#509]
php bin/hyperf.php mine-extension:install mine-admin/code-generator --yes
No security vulnerability advisories found.
即将安装代码生成器插件、将会进行以下文件更改，请确认无误后继续：
+--------------------------------------+------+
| 文件                                 | 操作 |
+--------------------------------------+------+
| /opt/www/storage/languages           | 复制 |
| /opt/www/storage/view/code-generator | 复制 |
+--------------------------------------+------+
package [hyperf/view-engine] misses `extra` field in composer.json.
“package [hyperf/view-engine] misses `extra` field in composer.json.”
这个是什么错误?

**Comment by zds-s** [comment]
```shell

composer require hyperf/view-engine -vvv

```
