### ISSUE TITLE
使用hyperf的模型查询数据时，刷新API接口时，有50%的概率会报这个错误

### ISSUE THREAD

**Issue by magicento** [mineadmin/MineAdmin#57]
[2023-05-20 07:20:36 $12089.0]	WARNING	Server::check_worker_exit_status(): worker(pid=12102, id=11) abnormal exit, status=0, signal=11
A bug occurred in Swoole-v5.0.1, please report it.
The Swoole developers probably don't know about it,
and unless you report it, chances are it won't be fixed.
You can read How to report a bug doc before submitting any bug reports:
>> https://github.com/swoole/swoole-src/blob/master/.github/ISSUE.md
Please do not send bug reports in the mailing list or personal letters.
The issue page is also suitable to submit feature requests.

OS: Darwin 22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 21:00:17 PST 2023; root:xnu-8796.101.5~3/RELEASE_X86_64 x86_64
GCC_VERSION: Apple LLVM 14.0.0 (clang-1400.0.29.202)
PHP_VERSION : 8.1.12

**Comment by wilbur-yu** [comment]
这个问题我也遇到了
https://github.com/swoole/swoole-src/issues/4776

**Comment by kanyxmo** [comment]
这个问题我解决不了，得向swoole提issues : )

**Comment by 178441367** [comment]
接口会挂掉还是只是警告
