### ISSUE TITLE
有没有办法像fastapi框架一样，它的请求参数、验证、自动接口文档，是我见过最优秀简洁的做法。 

### ISSUE THREAD

**Issue by goophps** [mineadmin/MineAdmin#67]
痛点：
同一批请求入参，业务代码里接收所有入参的字段、另外一个地方的代码里书写所有入参字段的验证、再另外一个地方书写所有入参字段的接口文档。

(1)特别麻烦，重复性的工作。
(3)三个地方，有时候加字段减字段改字段，弄来弄去，结果是：很严重。

见过最优秀的做法：

1 办法一，参数入参：
![image](https://github.com/hyperf/hyperf/assets/49714224/cd7c89c4-683d-4f0d-b060-86f8b909ec2b)

2 办法二，请求体入参：
![image](https://github.com/hyperf/hyperf/assets/49714224/9b920762-cdb8-4026-aee2-166aceb70b8c)

Chat请求体：
![image](https://github.com/hyperf/hyperf/assets/49714224/4f119bbc-f59c-4d52-9132-2d52c5851ae6)

只需要这样做，入参自动做了验证了、接口文档自动生成了，特别简洁，特别规范，特别不容易出错。

**Comment by goophps** [comment]
> 抽空研究一下

哈哈哈，太棒了，发现了一个类似的接口文档composer包：tangwei/apidocs
几乎跟上面的需求很像，面象对象思想非常好。希望能集成这个进去

**Comment by kanyxmo** [comment]
集成的有，你可以研究研究

**Comment by goophps** [comment]
> 集成的有，你可以研究研究

昨晚研究一晚上，搞不定，没思路。你能把这个列入规划吗

**Comment by Death-Satan** [comment]
tangwei/apidocs +dto
