### ISSUE TITLE
系统设置中的动态配置表单的逻辑似乎写错了

### ISSUE THREAD

**Issue by tlerbao** [mineadmin/MineAdmin#68]
https://github.com/kanyxmo/MineAdmin-Vue/blob/main/src/views/setting/config/index.vue

此代码的149行开始 ，我理解的是 如果是checkbox类型，那么就检测 item.value的值，用户可以输入两种形式来确认checkbox的值，一种是 `1,2,3`，第二种是`[1,2,3]`，但是下面这么写，会永远命中第一个if，因为第二种也包括逗号

我理解的没错吧，好像要把else if提前

```
if (item.value && item.value.toString().indexOf(',') > -1 && item.input_type === 'checkbox') {
        item.value = item.value.split(',')
      } else if (/^\[/.test(item.value) && /\]$/.test(item.value)) {
        item.value = JSON.parse(item.value)
      }
```

**Comment by kanyxmo** [comment]
我改下
