### ISSUE TITLE
代码生成器模块与数据库匹配问题

### ISSUE THREAD

**Issue by 1351681837** [mineadmin/MineAdmin#71]
目前我生成了一个模块名为Member  数据库前缀为s 生成model的时候s_member不可以配置 但是s_members s_memberopp s_member_info 都可匹配上 设计上就这样的吗

**Comment by 1351681837** [comment]
是否可以改为仅匹配s_member和s_member_info呢

**Comment by 1351681837** [comment]
是否可以改为仅匹配s_member和s_member_*呢

**Comment by kanyxmo** [comment]
嗯，当前的确是不匹配 s_member这样的，后面优化一下

**Comment by 1351681837** [comment]
这段代码仅匹配s_member和s_member_*相关代码     preg_match(sprintf("/%s(\b|_[a-zA-Z0-9]+)/i", $module), $tmp)

**Comment by kanyxmo** [comment]
> 这段代码仅匹配s_member和s_member_*相关代码 preg_match(sprintf("/%s(\b|_[a-zA-Z0-9]+)/i", $module), $tmp)

哪个文件哪一行 ？

**Comment by 1351681837** [comment]
vendor/xmo/mine-core/src/Command/Creater/CreateModel.php&nbsp; 69和72行



??
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kanyxmo/MineAdmin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月14日(星期五) 上午10:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [kanyxmo/MineAdmin] 代码生成器模块与数据库匹配问题 (Issue #71)





  
这段代码仅匹配s_member和s_member_*相关代码 preg_match(sprintf("/%s(\b|_[a-zA-Z0-9]+)/i", $module), $tmp)
  
哪个文件哪一行 ？

**Comment by kanyxmo** [comment]
https://github.com/kanyxmo/mine/commit/3e557ae1a64da7fbc16038d6f0fa361c8c645836

**Comment by 1351681837** [comment]
好的，谢谢!



??
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kanyxmo/MineAdmin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月14日(星期五) 中午11:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [kanyxmo/MineAdmin] 代码生成器模块与数据库匹配问题 (Issue #71)





 
***@***.***
