### ISSUE TITLE
watch 不会监听文件变化热重启了

### ISSUE THREAD

**Issue by FlameMida** [mineadmin/MineAdmin#75]
version_compare(PHP_VERSION, '8.1', '>') && Event::wait();
这个wait方法好像阻塞住了watch 和 state方法的调用

**Comment by kanyxmo** [comment]
已去掉了 https://github.com/kanyxmo/MineAdmin/commit/ee27ac2d936e410141d17eabd1e82d0ae526caa8

**Comment by FlameMida** [comment]
不再优化一下这个工具吗
