### ISSUE TITLE
打包后index.html引入的js和css文件不存在

### ISSUE THREAD

**Issue by hongzheng666** [mineadmin/MineAdmin#76]
打包后index.html引入的js和css文件不存在,vite.config.js中是否应该加上
    base: "./",

**Comment by kanyxmo** [comment]
部署的时候网站不在根目录吗？

**Comment by hongzheng666** [comment]
部署是使用nginx部署吗，还没试过

我是在本地直接用live server打开的index.html的，就加了base: "./"

**Comment by kanyxmo** [comment]
不在这里加，在 .env 里改 VITE_APP_BASE
