### ISSUE TITLE
cascader 为什么只有第一级数据, 是我哪里写的不对吗?

### ISSUE THREAD

**Issue by xhlsmile** [mineadmin/MineAdmin#78]
![image](https://github.com/kanyxmo/MineAdmin/assets/46104510/52b08302-ba0c-4995-b913-14d67d98e50c)

`{
    title: '类目',
    dataIndex: 'category_id',
    search: true,
    hide:true,
    formType: 'cascader',
    multiple: false,
    expandTrigger:"hover",
    dict: {
      url: "category/tree",
    }, commonRules: [{ required: true, message: '类别必选' }],
    editDefaultValue: async (record) => {
      const response = await product.read(record.id)
      return response.data.name
    }
  }`

**Comment by kanyxmo** [comment]
cascader select-tree 用字典只会显示第一级，需要用arco官方的组件api自行给数据。
比如级联是 options
![image](https://github.com/kanyxmo/MineAdmin/assets/1711988/c38bd736-efe6-41c6-9577-829cd9d287b2)

在ma-form 或者 ma-crud 中这样使用
```js
const optionsData = [
{
        value: 'beijing',
        label: 'Beijing',
        children: [
          {
            value: 'chaoyang',
            label: 'ChaoYang',
            children: [
              {
                value: 'datunli',
                label: 'Datunli',
              },
            ],
          },
          {
            value: 'haidian',
            label: 'Haidian',
          },
          {
            value: 'dongcheng',
            label: 'Dongcheng',
          },
          {
            value: 'xicheng',
            label: 'Xicheng',
            children: [
              {
                value: 'jinrongjie',
                label: 'Jinrongjie',
              },
              {
                value: 'tianqiao',
                label: 'Tianqiao',
              },
            ],
          },
        ],
      },
      {
        value: 'shanghai',
        label: 'Shanghai',
        children: [
          {
            value: 'huangpu',
            label: 'Huangpu',
          },
        ],
      },
]
{
  formType:'cascader',
  // 
  options: optionsData
}
```
