### ISSUE TITLE
在ResubmitAspect中如果捕获到sql错误会抛出$code类型不正确的错误

### ISSUE THREAD

**Issue by UnrealRoad** [mineadmin/MineAdmin#79]
在ResubmitAspect中如果捕获到sql错误会抛出$code类型不正确的错误
![image](https://github.com/kanyxmo/MineAdmin/assets/34133693/7df2101b-7f5b-4654-a886-28cb445c097e)

**Comment by kanyxmo** [comment]
好的，我看看
