### ISSUE TITLE
我切换成七牛云, 但是我之前上传到本地的图片, 在获取的时候就会报错

### ISSUE THREAD

**Issue by xhlsmile** [mineadmin/MineAdmin#88]

**Comment by Death-Satan** [comment]
哪个版本

**Comment by xhlsmile** [comment]
![image](https://github.com/mineadmin/MineAdmin/assets/46104510/fe4fd43f-a0d9-4707-a950-9c0d4ed1cd24)

**Comment by kanyxmo** [comment]
之前上传的肯定没法移到七牛云了，需要自己迁移
