### ISSUE TITLE
Dockerfile构建不了镜像

### ISSUE THREAD

**Issue by lushaobo** [mineadmin/MineAdmin#90]
![图片](https://github.com/mineadmin/MineAdmin/assets/5574978/6acb3260-a389-4a91-a3aa-eb737395e625)

使用 docker build 镜像的时候发现，拉取某个资源出现Error，检查发现是 https://php.hernandev.com 这个网站已经异常了

**Comment by kanyxmo** [comment]
用hyperf 官方的docker 镜像吧

**Comment by lushaobo** [comment]
好的，多谢解答
