### ISSUE TITLE
[BUG] #[Resubmit] 防止重复提交问题

### ISSUE THREAD

**Issue by lushaobo** [mineadmin/MineAdmin#91]
目前测试了下 #[Resubmit] 注解，发现虽然返回正确的提示信息 【访问太频繁，请稍后访问】，但代码还是会执行，达不到预期的作用。

暂时不清楚是否bug，还是设计如此。目前如果想使用，那么代码层面需要做下幂等性处理。

**Comment by kanyxmo** [comment]
待测试后答复
