### ISSUE TITLE
模型生成代码可能需要优化

### ISSUE THREAD

**Issue by taobali32** [mineadmin/MineAdmin#92]
![image](https://github.com/mineadmin/MineAdmin/assets/30717763/bfac86ce-ab9d-46db-9277-678b88b3deeb)

 1. 上面的箭头 应该默认返回个 string.. 不然 
不会显示到$casts里面.
![image](https://github.com/mineadmin/MineAdmin/assets/30717763/fb62b392-655c-45c3-a936-5b073f92308d)

命令:
```sh
php bin/hyperf.php gen:model test_article --refresh-fillable --refresh-fillable --with-comments --path app/Test/Model/Api
```

数据库结构
![image](https://github.com/mineadmin/MineAdmin/assets/30717763/52b386ac-f582-44e5-930e-447df063f3d9)

**Comment by Death-Satan** [comment]
这是hyperf官方封装的命令，请往 [hyperf](https://github.com/hyperf/hyperf/issues) 提issue
